name: Build docs and create pull request

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Upgrade pip & install pdoc & the package
        run: |
          python -m pip install --upgrade pip
          pip install pdoc .
      - name: Run pdoc and commit
        run: |
          pdoc --math --logo logo.jpg -o docs rat
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          delete-branch: true
          commit-message: Add docs for ${{ github.ref_name }}
          title: Add docs for ${{ github.ref_name }}
          body: Add docs for ${{ github.ref_name }}
          branch: docs-${{ github.ref_name }}
          base: main
          add-paths:
            docs/**